version: "3"
services:
  radius:
    image: frauhottelmann/daloradius-docker:1
    container_name: radius
    restart: always
    depends_on:
      - "radius-mysql"
    ports:
      - '1812:1812/udp'
      - '1813:1813/udp'
      - '80:80'
    environment:
      - MYSQL_HOST=radius-mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=radius
      - MYSQL_USER=radius
      - MYSQL_PASSWORD=ZxmXncUWooP
    volumes:
      - ./etc/clients.conf:/etc/freeradius/3.0/clients.conf
  radius-mysql:
    image: mariadb:10.3 
    container_name: radius-mysql
    restart: always
    environment:
      - MYSQL_DATABASE=radius
      - MYSQL_USER=radius
      - MYSQL_PASSWORD=ZxmXncUWooP
      - MYSQL_ROOT_PASSWORD=Vz2332nbnz2
    volumes:
      - "./radius-mysql:/var/lib/mysql"
  phpmyadmin:
    depends_on:
      - radius-mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: radius-mysql
      MYSQL_ROOT_PASSWORD: Vz2332nbnz2 
  pptpd:
    depends_on:
      - "radius"
    image: srgazh/pptpd:latest
    container_name: pptpd
    volumes:
      - ./etc/pptpd.conf:/etc/pptpd.conf
      - ./etc/ppp/pptpd-options:/etc/ppp/pptpd-options
      - ./etc/radiusclient.conf:/etc/radiusclient/radiusclient.conf
      - ./etc/servers:/etc/radiusclient/servers
      - ./log:/var/log
    network_mode: "host"
    privileged: true
    restart: always